CREATE TABLE IF NOT EXISTS trades (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trade_id VARCHAR(128) NULL COMMENT '交易所订单ID',
  symbol VARCHAR(32) NOT NULL COMMENT '交易对，如 BTC/USDT',
  direction ENUM('long', 'short') NOT NULL COMMENT '交易方向',
  entry_price DECIMAL(20, 8) NOT NULL,
  exit_price DECIMAL(20, 8) NULL,
  quantity DECIMAL(20, 8) NOT NULL,
  leverage INT UNSIGNED NOT NULL DEFAULT 1,
  entry_time DATETIME NOT NULL,
  exit_time DATETIME NULL,
  pnl DECIMAL(20, 8) NOT NULL DEFAULT 0,
  pnl_percentage DECIMAL(10, 4) NOT NULL DEFAULT 0,
  fee DECIMAL(20, 8) NOT NULL DEFAULT 0,
  status ENUM('open', 'closed') NOT NULL DEFAULT 'open',
  entry_reason TEXT NULL,
  exit_reason TEXT NULL,
  tags JSON NULL,
  notes LONGTEXT NULL,
  screenshots JSON NULL,
  rating TINYINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_trade_id (trade_id),
  KEY idx_trades_symbol (symbol),
  KEY idx_trades_status (status),
  KEY idx_trades_direction (direction),
  KEY idx_trades_entry_time (entry_time),
  KEY idx_trades_exit_time (exit_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_summary (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  date DATE NOT NULL,
  total_pnl DECIMAL(20, 8) NOT NULL DEFAULT 0,
  trade_count INT UNSIGNED NOT NULL DEFAULT 0,
  win_count INT UNSIGNED NOT NULL DEFAULT 0,
  loss_count INT UNSIGNED NOT NULL DEFAULT 0,
  total_fee DECIMAL(20, 8) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_daily_summary_date (date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
